### ISSUE TITLE
Re-Opening window doesn't show nodes

### ISSUE THREAD

**Issue by RomanZhu** [KumoKairo/Entitas-Visual-Jam#2]
If you open window for the first time - it loads ok
If you close it, and open again - nodes are loaded, but not shown (if Unity completes context switch - they are visible again)

I think there is serialization problem somewhere

Quick fix is to fully drop state in VisualEntitasGraphWindowOpener
```
        public void OnFocus()
        {
            Facade.RemoveCore(VisualEntitasFacade.Name);
            _facade = null;
        }
```

Btw i'm really enjoying  your crisp code and the way it's structured with PureMVC

**Comment by KumoKairo** [comment]
Cool, this is a neat addition, thanks for the advise!
Btw which version of Unity were you using when you got this bug?

**Comment by RomanZhu** [comment]
2017.3 as i recall
it it's wrong - i will fix it after work

**Comment by RomanZhu** [comment]
Same goes for Unity 2017.3.0f3 and Unity 2017.1.1f1
It's not a bug
It's how their serialization works 

I almost killed myself when wrote node editor for scene UnityEvent visualization and editing https://youtu.be/SbuuzRSObOo (it parses whole scene and connects nodes) (based on Node Editor Framework and modified almost everything)

It can be fixed with use of ScriptableObjects, as they can be serialized and then deserialized after context switch

**Comment by KumoKairo** [comment]
> It can be fixed with use of ScriptableObjects, as they can be serialized and then deserialized after context switch

I have intentionally skipped Scriptable Objects usage as although they require less fiddling with serialization, they tend to become too slow on larger object sizes than a simple ad-hoc text-based serialization (as we don't need to fidget back and forth between C# and C++ parts of Unity)

It is a valid solution though, depends on a use case.

And yeah, Unity Events and custom editors for them was a huge pain point lately, it has some internal serialization bugs which need certain workarounds.

**Comment by RomanZhu** [comment]
I guess i can close it now.
Do you have any plans for that project?

Also, i enjoyed your last presentation about ECS and showed it to everyone on job, to my friends and even to my grandma :D

**Comment by KumoKairo** [comment]
> Do you have any plans for that project?

Not really, not in current context. 
The story is that while implementing it I realized that we can actually get along completely without the core code generator. Making Entitas work with Generics instead of hardcoded preallocated components. So this project was a tide turner for me as we have dropped "vanilla" Entitas altogether and created our own ECS framework from scratch that works with generics and doesn't do any preallocation of components on a per-entity basis (it's more light on memory while maintaining overall performance)

> Also, i enjoyed your last presentation about ECS and showed it to everyone on job, to my friends and even to my grandma :D

Thanks :)

**Comment by RomanZhu** [comment]
https://github.com/KumoKairo/Generic-Entitas-Proof-of-concept is it what you are talking about?
or https://github.com/yosadchyi/Entitas.Generic this one?
they seems abandoned .-.

**Comment by KumoKairo** [comment]
I don't remember about proof-of-concept repo, xD 
I don't even know why this "proof of concept" is on github as it's just a doodle about the initial idea.
But it's possibly something I used as an initial guide to make current version. 
We don't opensource our in-house generic ECS framework because we use just it to suit our needs. Maintaining a public version of frameworks is usually a lot of overhead and a lot of excessive protection code all over the place (one can't suit everyone). 

As for the Generic Entitas wrapper - it's a very good concept and execution, but still has overhead of preallocating components. They most likely don't update it because when they shared it with Entitas community everyone has ridiculed them about "how can it possibly work without code generator". So they had no choice but to continue developing it in-house too (I'm pretty sure that this is the case).
